config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many : comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_post

  def create
    @post.comments.create!(comment_params)

    redirect_back(fallback_location: root_path)
  end

  def destroy
    comment = Comment.find params[:id]
    comment.destroy

    redirect_back(fallback_location: root_path)
  end

  private
  def load_post
    @post = Post.find params[:post_id]
  end

  def comment_params
    params[:comment][:user_id] = current_user.id
    params.require(:comment).permit(:user_id, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :load_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    Post.create!(post_params)

    redirect_to root_path
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
  end

  def update
    @post.update!(post_params)

    redirect_to root_path
  end

  def destroy
    @post.destroy

    redirect_to root_path
  end

  private
  def post_params
    params[:post][:user_id] = current_user.id
    params.require(:post).permit(:title, :content, :user_id)
  end

  def load_post
    @post = Post.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>J</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <h1>글 수정하기</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>글 목록입니다.</h1>
  <%= link_to "글 생성하기", new_post_path %>

  <% @posts.each do |post| %>
    <h4>
      <%= link_to post_path(post) do %>
        글의 제목 : <%= post.title %>
      <% end %>
    </h4>
    <h6>조회수 : <%= post.view_count %></h6>
    <p>글의 내용 : <%= post.content %></p>
    <%= link_to "수정", edit_post_path(post) %>
    <%= link_to "삭제", post_path(post), method: :DELETE %>
    <br><br><br>
  <% end %>
</div>

app/views/posts/new.html..erb
<div class="container">
  <h1>글 생성하기</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2><%= @post.user&.name %></h2>
<p><%= @post.content %></p>


<%= form_for(@comment, url: post_comments_path(@post)) do |f| %>
  <%= f.label :body, "댓글내용" %><br>
  <%= f.text_area :body %><br>

  <%= f.submit "제출" %>
<% end %>

<% @comments. each do |comment| %>
  <h2><%= comment.user&.name %></h2>
  <p><%= comment.body %></p><br><br>
  <%= link_to "삭제", post_comment_path(@post, comment), method: :delete %>
<% end %>